server:
  port: 8888
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  # Spring AI 配置
  ai:
    # 智谱AI大模型配置
    zhipuai:
      api-key: "3a6d297d29284ed6871cfa9093f5bf14.mzwgtUNMpmYz8ihn"  # 配置 API Key
      base-url: "https://open.bigmodel.cn/api/paas"   # 配置 模型地址
      chat:
        options:
          model: glm-4.5
      embedding:
        options:
          model: embedding-3 # 使用的嵌入模型名称（embedding-3）
          dimensions: 256 # 嵌入向量的维度（256维）

    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8080 # mcp服务url

    # 向量存储配置
    vectorstore:
      redis:
        initialize-schema: true # 启动时自动创建Redis向量索引结构（首次部署需开启）
        prefix: sangeng_rag_prefix # Redis键名前缀，用于区分不同应用的向量数据
        index: sangeng_rag_index # Redis向量索引名称

  # 数据源配置
  data:
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis服务器连接端口（默认6379）